### ISSUE TITLE
Browser is blur :-(

### ISSUE THREAD

**Issue by usama-asfar** [auchenberg/vscode-browser-preview#100]
Hello, I love this extension and very useful but the browser preview is blur 
Can I able to fix this issue?
![Capture](https://user-images.githubusercontent.com/42825498/57056794-59f20800-6cc2-11e9-8697-a8fa9496b28a.PNG)

**Comment by auchenberg** [comment]
Potential dup of https://github.com/auchenberg/vscode-browser-preview/issues/92
