### ISSUE TITLE
Consolidate the command palette menu

### ISSUE THREAD

**Issue by johnpapa** [auchenberg/vscode-browser-preview#11]
There are 2 menu options that appear to do the same thing

![image](https://user-images.githubusercontent.com/1202528/51256557-b3346680-1973-11e9-8d8f-be70f927d7b1.png)

- Browser: Show Browser Preview
- View: Show Browser Preview

If they are different, perhaps clarify in the readme. If they are indeed the same, consolidate them

**Comment by auchenberg** [comment]
I renamed the command to be more consistent. VS Code Core contributes the two others automatically, and I can't hide them.
