### ISSUE TITLE
Support for Code Server/Visual Studio Online

### ISSUE THREAD

**Issue by h1nk** [auchenberg/vscode-browser-preview#118]
I wanted to see if this extension would work in [code-server](https://github.com/cdr/code-server) just for fun, but sadly it does not:

![image](https://user-images.githubusercontent.com/12993584/63554956-ab9ef680-c52e-11e9-9a31-a27864ee2bc9.png)

I'm going to assume that this is well outside the realm of supported use cases, but I still wanted to ask if there is any way to get this to work.

**Comment by auchenberg-stripe** [comment]
If you open up DevTools and look at the console, do you see anything? Or what about in the output panels, @h1nk ?

**Comment by trigun539** [comment]
Yeah, this would be great if it could work with code server.

**Comment by h1nk** [comment]
Chromium wasn't even installed in the Docker container I was running. It does _work_ once installed, but entering anything into the address bar didn't seem to work and there was a bunch of other usability problems.

**Comment by auchenberg** [comment]
Given that Microsoft now have shipped http://online.visualstudio.com/, I'm renaming this issue to support of VS Online.

**Comment by lostintangent** [comment]
It would be amazing if we could add VSO support! 🤗 Is there anything our team (the VSO team) could do to help?

**Comment by auchenberg** [comment]
@lostintangent A model I explored in the early days was to run the Chrome instance on the remote instance to allow for example and IPad show chrome content rendered from the Linux box. Today the extension is marked as a UI extension, so it would require an API to declare the extension to remote based on what context the it's run in. Have you landed such apis?

**Comment by auchenberg** [comment]
Extension adopted to run as a workspace extension in VSC's case. Ping @lostintangent  https://github.com/auchenberg/vscode-browser-preview/issues/125

**Comment by lostintangent** [comment]
@auchenberg I just tested the bits in master, and it works in a VSO environment, including in the browser! The Live Share integration also works, which is pretty sick to see in the browser. Can you ship this update? 😎

**Comment by auchenberg** [comment]
Landed in v0.6.0

**Comment by obikay200** [comment]
hey i came accross this and think its awsome, have you got the setup steps to get this woking in code server? ive tried installing chrome but its not working...

any help would be much appreciated

**Comment by auchenberg** [comment]
@obikay200 What errors do you see?

**Comment by obikay200** [comment]
Thanks very much for the quick response, but i updated to the latest release of code-server ( 3.0.1 ) rather than latest and set permissions on the chrome binary and now it works!

**Comment by auchenberg** [comment]
Glad to hear!

**Comment by 8thHalfHour** [comment]
Sorry to come along this so late, but this is not working for me when running the extension in code-server on Linux Mint 20. It works great in VSCode on that same system, but not in code-server. I keep seeing mention that chromium needs to be installed on the same system, and it is, but I also see something in these messages about setting specific permissions on the chromium binary. Can any of you explain what those permissions should be set to and give basic instructions for setting it? I am pulling my hair out trying to figure it out, and this is a go-to extension for my workflow. I’d massively appreciate it; plus it can be here for other poor saps like me trying to figure it out, Lol. 

Setup:
- Code-server v3.9.3
- Chrome and Chromium browsers both installed locally

If you see something else I’m missing, please let me know.

**Comment by titogarrido** [comment]
Hi, I am running a code-server on ubuntu 18.04 and installed chromium-browser... When I execute via terminal, chrome works and open using an external X... But when I try it from Browser Preview it shows just a blank screen. How can I fetch errors for it?

![image](https://user-images.githubusercontent.com/333484/119054362-e18c3b80-b99d-11eb-9cac-88128a3ac836.png)
![image](https://user-images.githubusercontent.com/333484/119054390-ecdf6700-b99d-11eb-9a7f-3c209c5d84fa.png)

From webconsole:
```
Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.
    R main.js:196
    <anonymous> main.js:194
main.js:196:16
Uncaught (in promise) TypeError: navigator.serviceWorker is undefined
    createWebviewManager main.js:266
    <anonymous> host.js:106
```
