### ISSUE TITLE
[Enhancement] - Allow adding this npm scripting

### ISSUE THREAD

**Issue by johnpapa** [auchenberg/vscode-browser-preview#12]
Imagine we can add a command to our npm scripts to open the browser preview to a specific url. That would be an awesome feature.

```
"cool": "concurrently \"npm run start\" \"code -browserpreview -url http://localhost:9626\"",
```

this would require some way to launch it, obviously, from the command line.

**Comment by auchenberg** [comment]
Added via new debugging support. See readme
