### ISSUE TITLE
Adopt the new extensionKind format 

### ISSUE THREAD

**Issue by egamma** [auchenberg/vscode-browser-preview#125]
As of VS Code 1.40 the `extensionKind` attribute in the `package.json` of the extension can be an array, pls see the [documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). 

We will be deprecating the `string` type for `extensionKind` property in favour of `string array` type.

The `extensionKind` attribute for the preview extension should be set to `["ui"]`. Indicating that the extension can only run as a UI extension.

**Comment by auchenberg** [comment]
Thanks for the heads up @egamma. Updated.
