### ISSUE TITLE
"Failed to launch chrome! spawn"

### ISSUE THREAD

**Issue by 4th3LuLz0fIt** [auchenberg/vscode-browser-preview#128]
I'm using the latest version of vs code and chrome dev as well. Whenever I try to view HTML code via browser preview I get the error below.  Any resolutions?

C:\Users\name\AppData\Local\Google\Chrome Dev\Application\chrome.exe" ENOENT

**Comment by auchenberg** [comment]
What path do you have Google Chrome installed at?

**Comment by 4th3LuLz0fIt** [comment]
Chrome would install its self to the user appdata folder in windows 10. I changed the path in browser view settings to that path but still had the same issues. I've figured the error is a permissions issue since appdata is a protected folder within the users folder.

I resolved the issue by using my mac pro to develop in. I've had no issues since then, thanks!
