### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by laoczvip** [auchenberg/vscode-browser-preview#131]
![1582807549(1)](https://user-images.githubusercontent.com/51748911/75446323-27787080-59a2-11ea-9b81-056f3fcaf7d2.jpg)
It's newly installed, but it's a blank page when it's opened
But he made such a mistake

![1582807874(1)](https://user-images.githubusercontent.com/51748911/75446810-1714c580-59a3-11ea-8949-91082e1f3980.jpg)

**Comment by auchenberg** [comment]
Do you have Google Chrome installed in the path mentioned in the notification?

**Comment by laoczvip** [comment]
It has been resolved, I have previously installed a pirated version of Google Chrome, and now I can install a genuine one.
