### ISSUE TITLE
Just a quick question...

### ISSUE THREAD

**Issue by pbmacsodak** [auchenberg/vscode-browser-preview#133]
Running Ubuntu Linux 18.04 - when I open up the preview and go to localhost:3000 - do you know what directory it is pointing to? I am trying to figure out how to get to my test files, but can't quite seem to figure out where I am pointing to by default.

I find similar behavior on Mac OS

It works fine in Windows :(

Thanks
Pat McClanahan

**Comment by auchenberg** [comment]
Browser Preview doesn't serve local files or start a local http server for you. You have to do this yourself. Like https://www.npmjs.com/package/http-server or https://www.hackerearth.com/practice/notes/simple-http-server-in-python/
