### ISSUE TITLE
browser preview only support SSL certified websites

### ISSUE THREAD

**Issue by AbhishekTaparia** [auchenberg/vscode-browser-preview#134]
Just this question. Does it only support SSL certified websites?

**Comment by auchenberg** [comment]
Browser Preview should work with non-https sites. Just like http://neverssl.com

**Comment by AbhishekTaparia** [comment]
Yeah this is working but supposedly if I type https://neverssl.com then it does not show for the advance setting option as we normally get in Chrome.

**Comment by bou2you** [comment]
Right. I found if I try to use the Browser Preview VS Code extension with a self-signed SSL certificate against a local domain I only get a blank screen.
