### ISSUE TITLE
Embed/enable DevTools inside preview

### ISSUE THREAD

**Issue by blizzardengle** [auchenberg/vscode-browser-preview#135]
I know this has been asked before #120 but is there anyway to support opening dev tools (and the console) in the browser preview?

Attaching to VS Codes debugger works to get console messages out, and I can run all the typical commands like `window.location.reload()`, but I really need the dev tools for classes I'm teaching online this semester.

**Comment by auchenberg** [comment]
There's not built-in option. You might be able to use `chrome://inspect` from another Chrome instance.

**Comment by blizzardengle** [comment]
The reason I was hoping to get the actual dev tools in your extension is so I don't have to constantly switch windows. Screen share works best if I limit it to just a window (VS Code) verses sharing my whole screen.

It's a first world problem I know; I am toying with the idea of making my own watered down version in JavaScript and then running that on the page I'm demoing. I'll leave this issue open for a few days in case I do that but feel free to close it if you need to. And thank you for getting back so fast!

**Comment by auchenberg** [comment]
Thanks for the feedback, and yes I think it would make sense to be able to pop up the DevTools, but it would require quite some work to make happen.

So let me rename this issue and keep it open. Maybe someone would have time to help with this?

**Comment by blizzardengle** [comment]
Okay I'm a little burned out but I created a clone of the features I needed from Chromium's developer tools. You should now be able to inject the [web-dev-tool.min.js](https://github.com/caboodle-tech/web-dev-tool/blob/master/web-dev-tool.min.js) script into any web page and have a working developer tool. The tool can be opened with key presses `F12` or `Ctrl + Shift + I` and by direct call to `WebDevTool.open()`. I have a [live demo](https://caboodle-tech.github.io/web-dev-tool/index.html) up if anyone is curious to try it out right away. This is all in the [GitHub Repo for Web Dev Tool](https://github.com/caboodle-tech/web-dev-tool).

**Can someone help me set this up with VScode Browser Preview?** I don't know where to do this but it should be possible to include [web-dev-tool.min.js](https://github.com/caboodle-tech/web-dev-tool/blob/master/web-dev-tool.min.js) in the extension and then inject it into every page on page load/ reload.

**Comment by texastoland** [comment]
This works out of the box for Edge Chromium with the [official extension](https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools). I assume Chrome integration could be implemented separately as well. Can this issue be closed?

**Comment by blizzardengle** [comment]
> Can this issue be closed?

@texastoland I would say no. My students use Mac and Linux in addition to Windows computers. This only works natively on a Windows computer.

**Comment by texastoland** [comment]
@blizzardengle I'm personally on Mac. The devtools are the exact same as Chrome. I just mean that this makes more sense as a separate extension as opposed to a feature.

**Comment by blizzardengle** [comment]
As @texastoland noted this works on Mac and Windows using Edge. I'm not a fan of having to use Edge and Linux support still missing but it works for the majority of my students so I'm closing this.

**Comment by A-ElNawawy** [comment]
@blizzardengle 
check this, it can be useful for you
https://www.youtube.com/watch?v=vHZPeohPHqo
