### ISSUE TITLE
Debugging the website that needs to be verified cannot enter Chinese

### ISSUE THREAD

**Issue by zhusjfaker** [auchenberg/vscode-browser-preview#136]
I can't switch input method and input account with Chinese in headless browser

**Comment by secreter** [comment]
me too,and also can't use copy /paste

**Comment by Clearlove-X** [comment]
I have encountered the problem that Chinese characters cannot be displayed normally

**Comment by Clearlove-X** [comment]
I solved it because my host is missing some related components
