### ISSUE TITLE
Browser preview not showing web page

### ISSUE THREAD

**Issue by Ipponz** [auchenberg/vscode-browser-preview#137]
When selecting the browser preview I only get the visual studio page. The page I am working on does not display.

**Comment by mochanekodev** [comment]
I just installed this on vscode and can't get my preview to load either. It seems to be changing the file path to something that obviously can't be opened. ie:

file path: C:\Users\UserName\Desktop\index.html
plugin changed path: http://c/Users/UserName/Desktop/index.html

**Comment by mochanekodev** [comment]
@Ipponz  I just realized what to do. Instead of running "Open Preview" or "Show Browser Preview," you have to specifically "Open Active File in Preview." Mine works now.

**Comment by WayneEllery** [comment]
@mochanekodev `Open preview` command works for me too
<img width="601" alt="Screen Shot 2020-05-08 at 6 45 38 pm" src="https://user-images.githubusercontent.com/1885695/81388790-26ab4a00-915c-11ea-8e0c-333aae171499.png">

**Comment by curtoneyoung** [comment]
how do you open active file in preview?
