### ISSUE TITLE
Enable Sound

### ISSUE THREAD

**Issue by jockrow** [auchenberg/vscode-browser-preview#140]
Can enable the sound, to example to use for google meeting or youtube?

**Comment by auchenberg** [comment]
I don't think this is supported via the current APIs we have available. Sadly. But let's keep it open.

**Comment by ntindle** [comment]
Would these two links help?
https://github.com/mattogodoy/hacker-sounds
https://github.com/wix-incubator/codio/blob/a8b0eb216fa4f6310494b8616d70a1dea507c59c/vscode/src/audio/Audio.ts#L39

**Comment by auchenberg** [comment]
@ntindle Sadly not. We need a API over the Chrome DevTools Protocol that can gives us audio, which we then need to play inside VS Code.

**Comment by ntindle** [comment]
Looks like it would need to be filed here https://bugs.chromium.org/p/chromium/issues/list?q=component%3Aplatform%3EDevTools%3EPlatform&can=1&start=0

**Comment by jockrow** [comment]
Ok, I understand that don't is direct problem for you. Thank you for your attention

**Comment by auchenberg** [comment]
Let's keep this open as an upstream issue. We should aim for this, but need a Chromium API.

**Comment by ntindle** [comment]
@auchenberg did you open an issue upstream or shall I?

**Comment by auchenberg** [comment]
@ntindle If you have time it would be great!

**Comment by ntindle** [comment]
Last question on if this would help https://github.com/google/audion before I file it. I was browsing and found this from google

**Comment by ntindle** [comment]
I was unable to find time to open an issue upstream. I'm sorry for the late update but I had a question that was unanswered and it slipped my mind to follow up.

**Comment by auchenberg** [comment]
Already tracked in https://github.com/auchenberg/vscode-browser-preview/issues/31 so closing
