### ISSUE TITLE
Feature: Option to enable self-signed SSL certificates

### ISSUE THREAD

**Issue by OliverKovacs** [auchenberg/vscode-browser-preview#142]
### Problem
The browser blocks unsafe connections. This is fine as default behaviour but really inconvenient when you are trying to debug a website that uses self-signed SSL certificates because it doesn't give you the option to do it anyway as most normal browsers do. ([you can try it with this link](https://self-signed.badssl.com/))
### Fix
After some research I found out that this can be fixed by adding the property `ignoreHTTPSErrors: true` to the object that is passed to the `puppeteer.launch()` method in the file /build/ext-src/browser.js at line: 35. ([see the relevant documentation](https://github.com/puppeteer/puppeteer/blob/v5.2.1/docs/api.md#puppeteerlaunchoptions))
### Request
This works fine if you want to get it to work at all cost but hardcoding it this way seems to be a very inelegant solution. I wonder if it would be possible for you to add an option in the extension settings to toggle this behaviour on and off. It doesn't appear to be a hard thing to implement but I don't have any expirience with making vscode extensions so i'm not sure how one would achive this.

**Comment by nshiell** [comment]
I also have this issue
