### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by rao123dk** [auchenberg/vscode-browser-preview#15]
I am getting an error "Unable to install because the extension 'auchenberg.vscode-browser-preview' compatible with current version '1.29.1' of VS Code is not found".

Spec :- 
Code :- v1.29.1
OS:- Ubuntu 18.04.1

**Comment by auchenberg** [comment]
Update your VS Code version to the newest version 1.30 and you should be able to install.

**Comment by hitmacreed** [comment]
hi, i have the same issue and i have lates version of vsCode
even if i install it manualy does not open , the reload button does not deseapear

**Comment by auchenberg** [comment]
Latest version is Version 1.30 from November. Please download from https://code.visualstudio.com/Download

**Comment by hitmacreed** [comment]
> Latest version is Version 1.30 from November. Please download from https://code.visualstudio.com/Download

yes it worked , weird my vsCode did not warn me about updates , well thank anyway

**Comment by rao123dk** [comment]
Yes, it works. Close this issue.
