### ISSUE TITLE
I use the portable version of chrome, it will not be opened using the system default browser, but will use the fixed path link of the chrome installation version,

### ISSUE THREAD

**Issue by heicks** [auchenberg/vscode-browser-preview#164]
![image](https://user-images.githubusercontent.com/12287943/94239186-0120b080-ff44-11ea-9825-f1fa450608ca.png)

this is my chrome path
![image](https://user-images.githubusercontent.com/12287943/94239309-2f9e8b80-ff44-11ea-931c-11ff8f84cb3d.png)

tools by https://github.com/cnjackchen/my-chrome
------

more plug-in fixed chrome path.. not work has any more plugin in this path issus

**Comment by auchenberg** [comment]
You can use the `browser-preview.chromeExecutable` setting to set your custom path. Documented in the readme.
