### ISSUE TITLE
Don't refresh page automatically

### ISSUE THREAD

**Issue by COD3BREAK3R** [auchenberg/vscode-browser-preview#165]
When I press Ctrl+S don't auto refresh the view.

**Comment by Liang-xujiu** [comment]
> 当我按Ctrl + S时，不会自动刷新视图。
yes,you can only click the fresh button

**Comment by Liang-xujiu** [comment]
> When I press Ctrl+S don't auto refresh the view.

yes,you can only click the refresh button

**Comment by auchenberg** [comment]
Browser Preview doesn't support automatic refreshing, just like your normal browser. Use webpack or similar to enable this for your local web server.
