### ISSUE TITLE
How to enable console log?

### ISSUE THREAD

**Issue by santiagowprr** [auchenberg/vscode-browser-preview#166]
Hi!
I'd like to be able to see the output of the console while using browser preview. Is that possible?

**Comment by yume-chan** [comment]
https://github.com/auchenberg/vscode-browser-preview#launch-and-debugging

With the Debugger for Chrome extension you can see console output in the Debug Console view.

**Comment by magusikrak** [comment]
@yume-chan that is a bunch of codes. What am I to do with it? Can you please guide me?

**Comment by sar** [comment]
> @yume-chan that is a bunch of codes. What am I to do with it? Can you please guide me?

Just install the [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) extension and create a `.vscode/launch.json` with the properties mentioned in the docs.

Here's a visual guide on [launching the debugger](https://github.com/auchenberg/vscode-browser-preview/blob/master/docs/DEBUGGING.md) with `browser-preview` attached that respects breakpoints and variable scopes.

**Comment by auchenberg** [comment]
Closer as the help is provided in the last comment.
