### ISSUE TITLE
automatically refresh the preview on file save

### ISSUE THREAD

**Issue by marc-guenther** [auchenberg/vscode-browser-preview#167]
It would be very cool if the preview could refresh itself automatically every time I save the file.

At the moment, there are no real quick workarounds that I have found:
- I can manually click the refresh button. Slow, needs the mouse, It seems there is no keyboard shortcut for this.
- I could map the "Open active file in Preview" to some key combination, but it opens a new preview every time, and also steals the focus, so that's not very practical either.

**Comment by auchenberg** [comment]
Browser Preview doesn't support automatic refreshing, just like your normal browser. The intention is to keep this a browser, and offload this to webpack or similar to enable this for your local web server.
