### ISSUE TITLE
Using vscode-browser-preview to retrieve cookies

### ISSUE THREAD

**Issue by GuillaumeBlin** [auchenberg/vscode-browser-preview#168]
Hi,
In an extension i'm designing, I need to connect to a service via a web page and retrieve the corresponding cookies. By now, i'm using puppeteer to launch an external chrome window. I would like to embed it into vscode directly and i though vscode-browser-preview may be of help to achieve so but i have no clue how to tackle this problem. Is there a way to launch vscode-browser-preview command and wait for a specific cookie to be set and retrieve it from my ts extension ?
Thanks in advance.
Best

**Comment by GuillaumeBlin** [comment]
Great work by the way :)

**Comment by auchenberg** [comment]
You might be able to use https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools to connect to the browser preview.

Closing as this is out of scope for the extension.
