### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by brianking** [auchenberg/vscode-browser-preview#172]
RE: https://open-vsx.org/extension/auchenberg/vscode-browser-preview

Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the Eclipse Publisher Agreement on or before January 8, 2021. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is explained in the Wiki (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

If you are the project maintainer, we urge you to claim the namespace for your extension(s). To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by brianking** [comment]
I just noticed the extension was published by someone else, but you still have the opportunity to claim the namespace and continue to publish.

**Comment by brianking** [comment]
@auchenberg Bringing this to your attention again in case you missed it.

**Comment by auchenberg** [comment]
I don't have an overview of the value publishing this extension to Open VSX, nor have I published https://open-vsx.org/extension/auchenberg/vscode-browser-preview which seems to have been done on my behalf.

@brianking Please remove this listen.

**Comment by brianking** [comment]
> I don't have an overview of the value publishing this extension to Open VSX, nor have I published https://open-vsx.org/extension/auchenberg/vscode-browser-preview which seems to have been done on my behalf.

@auchenberg Apart from your extension being available to many more users in applications that support VS Code extensions, some of the value is outlined in this post:
https://www.eclipse.org/community/eclipse_newsletter/2021/january/1.php

> @brianking Please remove this listen.

As the extension has an MIT license, we've taken over the publishing of the extension for now.

/cc @spoenemann
