### ISSUE TITLE
Browser Preview always shows Blank page(with Debugger for Chrome)

### ISSUE THREAD

**Issue by seiferthan** [auchenberg/vscode-browser-preview#173]
Dear Sir:

I appreciate that you developed this VSCode plugin. Before installing it, I have checked and confirmed that there had been Debugger for Chrome in my VSCode.

However, it always shows the "blank page," even I add the launch.json configuration 100% as your suggestion in the introduction tapped on the VSCode plugin marketplace. Besides, the title of the inside browser is always "about blank."

I wish to use the popular and wonderful plugin to learn HTML and other front-end skills. Please help me solve the problem. If you need more detail about my VSCode, I will be very cooperative.

Attachments are the screen of the issue and my launch.json page.
![Plugin_BrowserPreview_alwaysBlank_20210116](https://user-images.githubusercontent.com/20491184/104792207-9cca7b00-57d8-11eb-9242-a29dd9d8dc20.jpg)
![Plugin_BrowserPreview_jsonConfig_20210116](https://user-images.githubusercontent.com/20491184/104792215-a358f280-57d8-11eb-84b7-fda3270ea727.jpg)

**Comment by auchenberg** [comment]
What do you have running on `http://localhost:4000`? You need a local server, just like if you visited the url in Chrome.
