### ISSUE TITLE
Add support for Local file URLs 

### ISSUE THREAD

**Issue by christian-korneck** [auchenberg/vscode-browser-preview#18]
Browser Preview Version: 0.2.5
VS Code Version: 1.30.2 (1.30.2)
Platform: macOS 10.14.2
Chrome version: 71.0.3578.98 (Official Build) (64-bit)

Trying to open a valid file URL in Browser Preview (i.e. `file:///Users/myuser/myfile.html`) doesn't work:
- A blank page is displayed (no error message)
- The URL in the address bar changes from `file://<url>` to `file//<url>` (i.e. `file///Users/myuser/myfile.html`)
- the title bar changes to `Browser Preview (http://file///<url>)` (i.e. `Browser Preview (http://file///Users/myuser/myfile.html)` ).

The same file URL works in Chrome.

**Comment by michellocana** [comment]
I have a similar error, but with **blob://** files:
`Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME [blob:http://localhost:3000/72334931-d3fd-41ac-a5ba-bea316cee06b]`

**Comment by gokulkrishh** [comment]
@auchenberg @michellocana  Same here. Browser is not able to read blob URL's. Attaching screenshots.

<img width="1553" alt="screenshot 2019-01-22 at 6 39 22 pm" src="https://user-images.githubusercontent.com/2944237/51537681-31fa3980-1e75-11e9-9beb-560f4fb1de44.png">

Same URL works find in chrome.

**Comment by gokulkrishh** [comment]
@auchenberg I can see that in your `extension.ts` file. `localResourceRoots` property has only allowed access to the extension build folder only.  I think changing this might work as the [webview API documentation](https://code.visualstudio.com/api/extension-guides/webview#controlling-access-to-local-resources).

**Comment by Taariqq** [comment]
Only reason people are still using Brackets. Fantastic Live Preview that is second to none.
