### ISSUE TITLE
Feature request: Open browser in sidebar

### ISSUE THREAD

**Issue by lukavida** [auchenberg/vscode-browser-preview#181]
Hey, great plugin, wondering how much work would be required to enable showing the browser in the sidebar (similar to Explorer/Search/Source control/etc.)

I guess many could use it to keep notes in their favorite web app while developing, etc.

**Comment by auchenberg** [comment]
This would be out of scope for browser perview, as we can't find in all the UI etc. Maybe VS Code will allow editors to be dragged into the sidebar one day.
