### ISSUE TITLE
Unbound breakpoint when debugging

### ISSUE THREAD

**Issue by dorin1000** [auchenberg/vscode-browser-preview#182]
I am using Live Server for hosting and trying to set up debug breakpoints. I have the Debugger for Chrome installed and the following launch.json configurations:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "browser-preview",
            "request": "attach",
            "name": "Browser Preview: Attach",
            "webRoot": "${workspaceFolder}"
        },
        {
            "type": "browser-preview",
            "request": "launch",
            "name": "Browser Preview: Launch",
            "url": "http://localhost:5500/Basics",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
The debugging console works and outputs properly, but setting breakpoints does not work. When setting them, they appear as red and when the code is executed the breakpoints do not trigger and switch to blank points saying that they are unbound. Tried to switch to running with Google Chrome and everyting works, but with Browser Preview it still does not. Am I missing some settings?

**Comment by auchenberg** [comment]
There's no technical difference between the two debuggers, as browser preview is simply starting the Chrome debugger behind the scenes,, so I'm wondering what it could be.

**Comment by auchenberg** [comment]
Closing due in activity.
