### ISSUE TITLE
Default Start URL set to "localhost/" not working..(ignore the double quotes)

### ISSUE THREAD

**Issue by lakshits11** [auchenberg/vscode-browser-preview#184]
Set default url to open to localhost not working

**Comment by kiliman** [comment]
This is what I have in my settings and it's working fine for me.

![image](https://user-images.githubusercontent.com/47168/111001551-fde27b00-8351-11eb-96a1-67d0aa0d5073.png)

![image](https://user-images.githubusercontent.com/47168/111001726-4a2dbb00-8352-11eb-9b30-5a0f98b7c068.png)

**Comment by lakshits11** [comment]
OK thank you BTW can u tell me which theme u r using? 😅😅

**Comment by kiliman** [comment]
I'm using the theme Cobalt2 by Wes Bos https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2

I'm also using the font Operator Mono Lig (a customized version of Operator Mono with ligatures) https://github.com/kiliman/operator-mono-lig

**Comment by lakshits11** [comment]
Thank you for your reply. 😀
