### ISSUE TITLE
"Updated" notification popping up semi-frequently

### ISSUE THREAD

**Issue by vith** [auchenberg/vscode-browser-preview#189]
https://github.com/auchenberg/vscode-browser-preview/blob/f3c9ceef3162be248cf50a926eb11695f12c0323/ext-src/telemetry.ts#L67

I'm not sure what this is supposed to mean to me as a user; for a long time I didn't know what extension was causing it. I think I see this pop up a few times a day for some reason.

Is this just leftover debugging that can be removed? Or maybe the message can be clarified, and/or only be displayed if some relevant configuration key actually changed?

**Comment by auchenberg** [comment]
@vith Good catch, yes this should be removed.

**Comment by jamilraichouni** [comment]
Hi!

First: Thanks for that extension!
Second: May you publish a new release where that message disappears?

Thank you,
Jamil

**Comment by auchenberg** [comment]
@jamilraichouni Done
