### ISSUE TITLE
WhatsUpWeb Support!!! 

### ISSUE THREAD

**Issue by f3d3r1c00** [auchenberg/vscode-browser-preview#191]
![what'supWeb_support](https://user-images.githubusercontent.com/77356557/113735030-21ec6e80-96fc-11eb-8b64-eab8d6cebda9.png)
one image worth a thousand words...
please update headless chromium version and eventually think about enabling use with scrapy-selenium for the next futere will be usefull to have it!!
Great extension nonetheless

**Comment by auchenberg** [comment]
Browser Preview is using your local Chrome or Edge instance behind the scene, so please check your Chromium version.
