### ISSUE TITLE
Blurry text/graphics on High DPI notebook (4K)

### ISSUE THREAD

**Issue by RobJacobson** [auchenberg/vscode-browser-preview#202]
I'm running this in VS Code on my Windows 10 notebook, which has a 4K display.

I installed vscode-browser-preview today but was disappointed with the display quality.  The text wasn't crisp and the images had major compression artifacts.  I've attached some side-by-side comparison shots with Firefox on my notebook.

Is this not rendering native HTML?  It almost looks like video with lossy compression.  

Thanks for the project!  

![Browser Preview 1](https://user-images.githubusercontent.com/23462125/122630364-dc430f00-d077-11eb-92ee-1103e806e74b.png)
![Browser Preview 2](https://user-images.githubusercontent.com/23462125/122630367-dea56900-d077-11eb-8bf6-777853c741f9.png)
![Browser Preview 3](https://user-images.githubusercontent.com/23462125/122630368-e06f2c80-d077-11eb-847c-60ce6de1c33f.png)

**Comment by auchenberg** [comment]
Thanks for the report! Probably same as https://github.com/auchenberg/vscode-browser-preview/issues/75

**Comment by RobJacobson** [comment]
> Thanks for the report! Probably same as #75

Thank you! I'll close this issue in favor of #75. However, the fact that this has been a "known issue" since 2019, and remains open today, disappoints me a bit. 😢 

Maybe I just have OCD, but viewing a "blurry version" of my website -- after working so hard to "make it pretty" -- is not a fun experience. I'd rather use an external browser.

**Comment by RobJacobson** [comment]
> Thanks for the report! Probably same as #75

Thank you! I'll close this issue in favor of #75. However, the fact that this has been a "known issue" since 2019, and remains open today, disappoints me a bit. 😢 

Maybe I just have OCD, but viewing a "blurry version" of my website -- after working so hard to "make it pretty" -- is not a fun experience. I'd rather use an external browser.
