### ISSUE TITLE
Improve sluggish, low fps rendering

### ISSUE THREAD

**Issue by fredrikaverpil** [auchenberg/vscode-browser-preview#21]
Scrolling is very sluggish on any web page (e.g. the startup vscode page). I just tried to go to YouTube and the videos were playing with low fps, perhaps around 10 or so... (I didn't do any scientific measuring).

Perhaps this is a known issue or known side effect of Chrome Headless?

I'm on a MacBook Air (11-inch, Early 2015) running macOS Mojave.

**Comment by max-frai** [comment]
+1 it lags a lot and after some time vscode not responding.

**Comment by auchenberg** [comment]
See https://github.com/auchenberg/vscode-browser-preview/issues/14

**Comment by auchenberg** [comment]
@pelotom Please try the newest release

**Comment by barbuza** [comment]
I'm experiencing blurred rendering on linux, extension version 0.4.0

![2019-03-13-163523_2560x1440_scrot](https://user-images.githubusercontent.com/37811/54283124-6dc89a00-45ae-11e9-9b1a-0b2d8da372e6.png)

system info

```
                          ./+o+-       barbuza@desktop
                  yyyyy- -yyyyyy+      OS: Ubuntu 18.04 bionic
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.15.0-46-generic
           .++ .:/++++++/-.+sss/`      Uptime: 2h 30m
         .:++o:  /++++++++/:--:/-      Packages: 2906
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.4.2
       .:+o:+o/.          `+sssoo+/    Resolution: 2560x1440
  .++/+:+oo+o:`             /sssooo.   WM: i3
 /+++//+:`oo+o               /::--:.   CPU: Intel Core i7-8086K @ 12x 5GHz [27.8°C]
 \+/+o+++`o++o               ++////.   GPU: GeForce GTX 1080 Ti
  .++.o+++oo+:`             /dddhhh.   RAM: 7168MiB / 32112MiB
       .+.o+oo:.          `oddhhhh+
        \+.++o+o``-````.:ohdhhhhh+
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.
```

**Comment by pitops** [comment]
I experience same issues as above. Any fixes?

**Comment by auchenberg** [comment]
@barbuza The blurry rendering should have been fixed in master. See https://github.com/auchenberg/vscode-browser-preview/issues/75

**Comment by kevinmarrec** [comment]
@auchenberg Still experiencing the issue with **0.5.0**

**Comment by auchenberg** [comment]
@kevinmarrec Interesting, so that's a high-dpi issue (4k). Can I get you to open a new issue with screenshots from your setup?

**Comment by kevinmarrec** [comment]
@auchenberg What are the elements you need on the screenshots ?

It seems to be same issue as @barbuza which has 1440p display.
![Screenshot from 2019-04-11 01-23-27](https://user-images.githubusercontent.com/25272043/55920015-74235380-5bf8-11e9-96aa-a5aa6884e3f1.png)

So yeah, high-dpi issue

**Comment by auchenberg** [comment]
Upstream Chromium issue on video streaming: https://bugs.chromium.org/p/chromium/issues/detail?id=781117

**Comment by kevinmarrec** [comment]
@auchenberg Have you any details about how it's related to my issue ? I tried to understand but I'm not sure what's goin on

**Comment by auchenberg** [comment]
@kevinmarrec See https://github.com/auchenberg/vscode-browser-preview/issues/92

**Comment by nickmccurdy** [comment]
Why not use a webview instead of headless Chrome?

**Comment by auchenberg** [comment]
@nickmccurdy VS Code don't allow low-level access to the Electron WebView, and is filtering web content that is hosted in the webview for XSS, etc. Essentially trying to avoid turning VS Code into a Web Browser.

**Comment by borekb** [comment]
The extension should open the Preview only when the macbook is being charged 😄. It's _very_ CPU & GPU intensive which I didn't realize and my battery went empty very quickly.
