### ISSUE TITLE
Vue/Nuxt: Preview consistently one save behind actual

### ISSUE THREAD

**Issue by adrianbw** [auchenberg/vscode-browser-preview#26]
Using Vue/Nuxt, which hot reloads code, the browser preview is very consistently showing me the state of the last change, rather than the one I just made. See attached screenshot where the "more" text in the browser has no underline, but preview is showing one.

MacBook Pro OSX latest
2.9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 560 4096 MB
Intel HD Graphics 630 1536 MB

<img width="1166" alt="screen shot 2019-01-22 at 11 38 13 am" src="https://user-images.githubusercontent.com/12662580/51554182-48cf6a80-1e3a-11e9-8283-e5da28ac74e8.png">

**Comment by auchenberg** [comment]
@adrianbw Interesting. Have you tried other frameworks that users HMR? Wondering if this is specific to Vue/Nuxt.

**Comment by sandiiarov** [comment]
The same issue with:
- React 16.7.0
- React Hot Loader 4.6.3

**Comment by adrianbw** [comment]
The only other system I use that does hot reloads is Meteor/Blaze and I can’t replicate the issue there.

**Comment by auchenberg** [comment]
Interesting. Wondering if this is related to Webpacks HMR. What webpack version are you using @adrianbw ?

**Comment by adrianbw** [comment]
The whole chain, in case it's useful:

`nuxt@2.3.4 -> @nuxt/webpack@2.3.4 -> webpack@4.27.1 `

**Comment by auchenberg** [comment]
@adrianbw Should be fixed in the newest release, please give it a try.
