### ISSUE TITLE
Viewport size is sometimes off on initial render

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/vscode-browser-preview#3]

**Comment by burkeholland** [comment]
I noticed that it seems to pick up the zoom level of VS Code as well. If you set the zoom to a 4, the page is zoomed in on as well.

**Comment by auchenberg** [comment]
Tried fixing this in https://github.com/auchenberg/vscode-browser-preview/commit/616cc557fc24d962ac04a44012b966766047a746
