### ISSUE TITLE
chrome://inspect not loading

### ISSUE THREAD

**Issue by giannif** [auchenberg/vscode-browser-preview#35]
Putting `chrome://inspect` in the location bar and hitting enter doesn't load the devtools page. If there's another way to do this, lmk. Love the project, thanks!

Chrome: Version 71.0.3578.98 
Mac OS: 10.14.2 (18C54)
VSCode: Version 1.30.2 (1.30.2)

**Comment by auchenberg** [comment]
You can't load Chrome internal Chrome pages from Browser Preview. You would have to do this in a new Chrome instance.

**Comment by giannif** [comment]
Gotcha. The docs say `Features: Attach Chrome DevTools via chrome://inspect`, which makes it seem to be a feature of `Browser Preview`. But it's a normal feature of Chrome that we've all been using already 

Also, how do I use devtools in `Browser Preview`

**Comment by auchenberg** [comment]
Setup network detection in port 9222, and you should see the open tabs showing for your previews.

![screen shot 2019-01-23 at 11 59 38 am](https://user-images.githubusercontent.com/173559/51633387-62d67f00-1f06-11e9-8123-31e9f90ded1f.png)
