### ISSUE TITLE
Add support for window.open

### ISSUE THREAD

**Issue by gjsjohnmurray** [auchenberg/vscode-browser-preview#40]
Some web apps use window.open to pop up secondary pages. It'd be nice if Browser Preview could handle this kind of thing:

```window.open("https://code.visualstudio.com","_blank","width=600,height=400");```

**Comment by auchenberg** [comment]
@gjsjohnmurray Interesting case. I'm wondering if there's an API for this over https://chromedevtools.github.io/devtools-protocol/tot/Page

**Comment by auchenberg** [comment]
There seems to be https://chromedevtools.github.io/devtools-protocol/tot/Page#event-windowOpen, so it should be trivial to listen for this, and open a new browser view instance with the url. Wanna take a stab at it @gjsjohnmurray ?

**Comment by gjsjohnmurray** [comment]
I've updated to 0.2.6 and now window.open produces a new tab, but it doesn't load from the url specified in the window.open call

For example, go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open and click on the "Try it" button on the right-hand pane.

In my testing using that page, sometimes the new tab shows URL 'about:blank' and other times it loads the page my browser-preview.startUrl points to, which is https://code.visualstudio.com

**Comment by auchenberg** [comment]
@gjsjohnmurray Can you try in 0.2.7? Issue should be fixed now.

**Comment by gjsjohnmurray** [comment]
Yes, fixed. Thanks for the prompt service.
