### ISSUE TITLE
v0.2.6 default browser undefined

### ISSUE THREAD

**Issue by MartinoMensio** [auchenberg/vscode-browser-preview#44]
Hi,
From the recent update 0.2.6 that introduced the custom location of Chrome, the extension default browser is not working. Downgrading to 0.2.5 makes the extension work again without changing anything else.

## Details of the error

A popup error appears: "cannot read property 'remoteDebugPort' of undefined" when I run the configuration "launch".

`launch.json`
```jsonc
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "browser-preview",
            "name": "Browser Preview: Attach",
            "request": "attach"
        },
        {
            "type": "browser-preview",
            "request": "launch",
            "name": "Browser Preview: Launch",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

My app is simply an angular app already running on port 4200.

## Steps to reproduce the issue

Simply follow the instructions given on this guide https://medium.com/@MarkPieszak/debugging-angular-cli-inside-vscode-with-browser-preview-8dcc4b18ed64

## System

auchenberg.vscode-browser-preview: 0.2.6
msjsdiag.debugger-for-chrome: 4.11.1
vscode: 1.30.2
chrome: 71.0.3578.98 installed through homebrew cask
os: Mac OSX 10.14.3

I have no idea on how to debug the extension, I can just confirm that it works using 0.2.5.

**Comment by auchenberg** [comment]
Sorry about that @MartinoMensio, please update to the newest version and let me know how it works.
