### ISSUE TITLE
Typing ineffective after tabbing to next input field

### ISSUE THREAD

**Issue by gjsjohnmurray** [auchenberg/vscode-browser-preview#45]
1. Go to https://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_submit for a simple two-field form.
2. Type new value into the first field.
3. Press TAB. Focus appears to move to the second field as desired.
4. Try typing a new value here. Nothing happens.
5. Click mouse into the second field. Now typing works.

**Comment by gjsjohnmurray** [comment]
Doesn't seem to fix what I'm seeing. To demonstrate I've created a fiddle at https://jsfiddle.net/gjsjohnmurray/Lst6xe0g/

1. Point Browser Preview 0.3.0 at that URL.
2. Click the Run button.
3. Click into the first textfield in the form on the lower right.
4. Type some text and press Tab.
5. Highlight moves to the second field but typing there doesn't put anything into it.

 
![image](https://user-images.githubusercontent.com/6726799/53010028-b3bd9280-3434-11e9-9222-56fe7d7f4168.png)

**Comment by auchenberg** [comment]
@gjsjohnmurray Does the original demo page work for you?

**Comment by gjsjohnmurray** [comment]
No it doesn't. Here's my About info:

Version: 1.32.0-insider (user setup)
Commit: a75cf6e4b4317de0bf38284af255bdf0089deb68
Date: 2019-02-19T06:18:01.215Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by auchenberg** [comment]
@gjsjohnmurray Interesting. Works here on MacOS.

What's your Chrome version? Mine is Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by auchenberg** [comment]
Ah, actually seems to be a problem with the VS Code Insiders edition. Tested and validated in VS Code Stable so far.

    });

**Comment by auchenberg** [comment]
@gjsjohnmurray Please try version `0.3.1`

**Comment by gjsjohnmurray** [comment]
0.3.1 resolves this in Insiders. Thanks!
