### ISSUE TITLE
Javascript initiated dialog (e.g. alert) freezes Browser Preview

### ISSUE THREAD

**Issue by gjsjohnmurray** [auchenberg/vscode-browser-preview#46]
If script on a page invokes ```alert('Hello world')``` the page becomes unresponsive. Nor does the alert appear.

The issue probably affects ```confirm``` and ```prompt``` in the same way, plus any dialog arising from ```onbeforeunload```.

I suspect Browser Preview needs to listen for [Page.javascriptDialogOpening](https://chromedevtools.github.io/devtools-protocol/tot/Page#event-javascriptDialogOpening) on which I guess it'll receive ```hasBrowserHandler``` as ```false```. Then it could invoke a [VSCode equivalent](https://code.visualstudio.com/api/references/vscode-api#window) and call [Page.handleJavaScriptDialog](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-handleJavaScriptDialog) with the result.

Perhaps JS ```alert``` would map to ```Window.showWarningMessage```, and ```confirm``` to ```showInformationMessage```, and ```prompt``` to ```showInputBox```.

@auchenberg - based on how rapidly you turned around #40 I'm hoping you can do something with the above. Sorry, I'm not currently set up to offer you a PR.

**Comment by auchenberg** [comment]
Ah, good catch! Hadn't though of that. We should indeed look into this.

**Comment by gjsjohnmurray** [comment]
Looks good, though I wonder if the VSCode message that alert() produces should be modal, to mimic the way a browser alert() prevents user interaction anywhere else.

**Comment by auchenberg** [comment]
@gjsjohnmurray We don't have such thing as far as I'm aware.

**Comment by gjsjohnmurray** [comment]
Isn't that what the ```modal``` property of ```MessageOptions``` does?

https://code.visualstudio.com/api/references/vscode-api#MessageOptions
