### ISSUE TITLE
Configuration settings access path

### ISSUE THREAD

**Issue by peterblazejewicz** [auchenberg/vscode-browser-preview#48]
This looks wrong:
https://github.com/auchenberg/vscode-browser-preview/blob/a9d9c5354ca915f4fed9e41cbabd4037b1eabb2e/ext-src/extension.ts#L173
```ts
if (b.config.settings.startUrl == url) {
```
as AFAIK the other code sets that property directly on the configuration object.

Thanks!

**Comment by auchenberg** [comment]
Nicely spotted @peterblazejewicz !
