### ISSUE TITLE
Support for objectURLs created through window.URL.createObjectURL(blob)

### ISSUE THREAD

**Issue by Jaans** [auchenberg/vscode-browser-preview#51]
First of all, great job and thank you!

Our site creates a lot of [objectURLs ](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL )for blobs that are fetched from APIs, to display those blob data (Images, Stylesheets, Markup, etc.). It invokes the browser to create them via calls to `window.URL.createObjectURL(blob)` and the resulting URL takes the form of 
`blob:https://www.yoursite.com/{UUID-here}`. 

Whilst it works without issue in Chrome, the below error is logged to the Debug Console of VS Code:
```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME [blob:http://www.yoursite.com.au:8081/7ba1635a-4cdb-4af6-8702-f364909e3aa1]
```
Is there some configuration we are missing or is this support not yet available? If the latter, please consider this our +1 vote for it.

Thanks again.

**Comment by auchenberg** [comment]
Interesting case @Jaans! Would you be able to put together a demo page that would enable us to test this?

**Comment by auchenberg** [comment]
Looks like to be an upstream Chrome headless issue, https://github.com/GoogleChrome/puppeteer/issues/3463

Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=902918&desc=2

**Comment by Jaans** [comment]
Thanks for the update and finding under Chromium bugs. Do you still need me to create a demo page, or is the repro from the bug report sufficient?

**Comment by Jaans** [comment]
Was Chrome 71, now 72 :-) Hoo-Rah! It works now.
Thank you for your help. Much appreciated.
