### ISSUE TITLE
novice questio (need help)

### ISSUE THREAD

**Issue by demosglok** [auchenberg/vscode-browser-preview#52]
i'm on windows. chrome 71.0.3578.98, vscode 1.30.2
i'm coding in VueJS.

I installed browser preview.

launch.json after adding configurations
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}"
    },
    {
      "type": "browser-preview",
      "name": "Browser Preview: Attach",
      "request": "attach"
    },
    {
      "type": "browser-preview",
      "request": "launch",
      "name": "Browser Preview: Launch",
      "url": "http://localhost:3000"
    }
  ]
}

once I press "browser preview" button on sidebar, window opens with "https://code.visualstudio.com/"
instead of my app.

once I press "debug" start debugging with "browser preview" selected, I see blank screen (localhost:3000/) and no app there.

though "debug " start debugging with "chrome" also give empty page.

may be that's because latest vue tends to run development server with "npm run serve" instead of "npm start"?

**Comment by auchenberg** [comment]
What url does your local VUE development server run on?

**Comment by demosglok** [comment]
I found setting to set default url for browser preview. actually when I run vue app in devmode manually it uses port 8080. however from "browser preview extension" description I expected that once installed, it'll run devserver itself. like "npm start" and set PORT envvar to match opening url and devserver.

do you want to say that I need first run devserver and only then open browser preview?

**Comment by auchenberg** [comment]
@demosglok You can use a `launch.json` configuration for this together with a pre task that starts your dev server. See https://www.nealbuerger.com/2017/09/08/vscode-launch-create-react-app-and-chrome-with-launch-json/

Browser Preview is a browser, just like Chrome, and won't start a local dev server for you. But you can configure Browser Preview with other parts of VS Code to automate the workflow.
