### ISSUE TITLE
Feature: Inspect element -> open source file 

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/vscode-browser-preview#55]
This feature is new "inspect element" mode that allows you to Inspect an element in VS Code. When clicking instead of seeing the element in a DOM Explorer, you instead see the source file for the component that created the DOM element. Think of this as the DOM explorer for the Component-age, or a built-in React DevTools like experience in Browser Preview.
 
Initial plumbing in https://github.com/auchenberg/vscode-browser-preview/tree/inspect

![demo](https://user-images.githubusercontent.com/173559/52542912-a1b76200-2d59-11e9-9bd7-ed7ef7ac9287.gif)

Prototype is hacked together for React.js, and demo is showing a out of box create-react-app.

Actions:
- [x] Add inspect button to toolbar
- [x] Get position for DOM element
- [x] Resolve position into DOM element id
- [x] Add rendering of element highlighting in Canvas 
- [x] Map DOM element ID to source position using https://github.com/auchenberg/element-to-source
- [x] Open file in VS Code

**Comment by yozlet** [comment]
@auchenberg Any more work planned on this? It's a killer feature, and you have enough users that putting out a partially-working "alpha" version might get some traction for contributions. (Especially amongst devs involved with unsupported frameworks.)

**Comment by auchenberg** [comment]
@yozlet Needs a refactor, and highlighting needs to be adjusted to the new emulation mode, so a bit of work ahead.

**Comment by auchenberg** [comment]
@yozlet First version has been released. Handling of scaled viewports still needs to get there.
