### ISSUE TITLE
Duplicate previews when switching themes

### ISSUE THREAD

**Issue by beriberikix** [auchenberg/vscode-browser-preview#58]
On a fresh run of Visual Studio Code, after I launch Browser Preview and cycle through Themes, I see duplicate windows open up.

Steps to reproduce:
• Open a fresh instance of VSC
• Click the Browser Preview icon in the activity bar
• The preview launches in a new column
• cmd-shift-P to change the color theme.
• Move up or down with arrows and after the first theme and a second preview launches in the second column

I also noticed that if I close the left-most column, when I try to change the color theme, a new column with a duplicate preview launches.

![screen shot 2019-02-11 at 11 02 27 am](https://user-images.githubusercontent.com/178376/52586748-1ab3c980-2ded-11e9-836b-dcc6b5fe0e2e.png)

macOS: 10.14.3
VSC: 1.31.0
Browser Preview: 0.2.8
Chrome: 71.0.3578.98, 64-bit

**Comment by auchenberg** [comment]
Interesting case @beriberikix. Probably a result of me mis using the sidebar as toolbar.

**Comment by beriberikix** [comment]
My hunch, and I don't have any data to back it up, is that there's something in the reload logic when switching themes that's causing something to fire. Is it possible its a bug in VSC itself?

**Comment by mayc0njr** [comment]
Same problem here. Actually, even without any open browser tab, switching or previewing another theme will launch one tab.

**Comment by yoyoys** [comment]
Any news? It's really annoying

**Comment by auchenberg** [comment]
Seem to be resolved in VSC 1.42.1
