### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms

### ISSUE THREAD

**Issue by cosminalco** [auchenberg/vscode-browser-preview#68]
Actually is working perfectly but only after the second time I launch the debugger, the first time I get this error:
![screenshot 15](https://user-images.githubusercontent.com/42435633/53693982-7cde6980-3db0-11e9-9ef7-49620694e12e.png)

The newcomers may think the extension is not working.

Maybe is because of Debugger for Chrome extension I don't know, I would be happy just know if there is somewhere I can increase that delay.

My launch.json:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "browser-preview",
      "request": "launch",
      "name": "Browser Preview: Launch",
      "url": "http://localhost:5000/",
      "webRoot": "${workspaceFolder}/public"
    }
  ]
}
```

**Comment by auchenberg** [comment]
@cosminalco Would you happen to have other Chrome instances running in your machine?

**Comment by cosminalco** [comment]
No, but maybe is because I'm using the portable version of VSCode from on a partition, Windows is on `C:` VSCode is in `D:/Apps/VSCode`

**Comment by eltoncezar** [comment]
Same issue here. Everything worked great till last week. But today I started getting this error. Can't make it work even after a second run.
I can confirm that there are no other Chrome instances running at the same time. I can also confirm that launching with Debugger for Chrome and the same configuration works just fine.

```
{
  "version": "0.2.0",
  "configurations": [
  // This do work
  {
    "name": "ng serve",
    "type": "chrome",
    "request": "launch",
    "preLaunchTask": "npm: start",
    "url": "http://localhost:4200/#",
    "webRoot": "${workspaceFolder}"
  },
  // This doesn't
  {
    "name": "Browser Preview: Launch",
    "type": "browser-preview",
    "request": "launch",
    "preLaunchTask": "npm: start",
    "url": "http://localhost:4200",
    "webRoot": "${workspaceFolder}"
  }]
}
```

**Comment by putopavel** [comment]
Same happens to me, but it gives me another error:
![image](https://user-images.githubusercontent.com/9091619/56508657-26c2b280-6525-11e9-884a-95736c426c59.png)
This is my `launch.json` file:
```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "browser-preview",
      "request": "launch",
      "name": "Browser Preview: Launch",
      "url": "http://localhost:8100",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```
BTW I use this for debugging an Ionic4 App and I'm running High Sierra.

**Comment by yoyoys** [comment]
I'm using OSX Mojave, same problem here with vuejs(cli3)

**Comment by eltoncezar** [comment]
@auchenberg when this fix will be available at the marketplace OR how can I test it today? can you provide some info? I'm not familiar with building vs-code extensions. Thanks in advance.

**Comment by auchenberg** [comment]
@eltoncezar I've pushed https://github.com/auchenberg/vscode-browser-preview/releases/tag/v0.5.4 which contains the fix

**Comment by eltoncezar** [comment]
many many many thanks! it's working again!

**Comment by auchenberg** [comment]
Yay, glad to hear @eltoncezar

**Comment by kevinbarabash** [comment]
I'm seeing this in 0.5.9.  I can work around it it by opening Browser Preview manually and then running the launch command.  This results in two windows so I close the one I opened manually.  Here's the launch config I'm using:
```
{
    "type": "browser-preview",
    "request": "launch",
    "name": "Browser Preview: Launch",
    "url": "http://localhost:9000",
    "webRoot": "${workspaceFolder}"
},
```
