### ISSUE TITLE
Feature: Add ability to open current open html file as file://<path>

### ISSUE THREAD

**Issue by daryldauphin** [auchenberg/vscode-browser-preview#71]
hello,

When I press the preview button it opens the vs code website. 

I want to open any html file I'm working on.

how do I change the setting for that?

**Comment by auchenberg** [comment]
Currently we don't support launching individual files, but you can start a local dev server like `npx http-server` and visit `http://localhost:3000` with browser preview.

I've renamed the issue for clarity.

**Comment by daryldauphin** [comment]
this is not a "live" preview extension?

**Comment by auchenberg** [comment]
No, it's a browser preview. A browser inside VS Code. You can combine it with live-server, or alike to have 'live preview"

**Comment by daryldauphin** [comment]
Ok cool,

I have the live server plugin  installed.

How do I combine them?

**Comment by ErickPetru** [comment]
@auchenberg what about using the `file:` URL scheme? Maybe it can be the default action only if there's no `launch.json` in the current workspace folder or if the current file is being edited directly (not in the workspace).

**Comment by warpdesign** [comment]
Would love the ability to open any file (using `file:`), not only url that requires a development server.

This would make developing/testing simple static files so much better than having to open a browser outside of Chrome.

What's needed to allow that? Maybe I can help.

**Comment by auchenberg** [comment]
@warpdesign A new command, looking for the active editor, get the path, and calls the command. See https://github.com/ritwickdey/vscode-live-server/pull/352/files#diff-4cbd5cd13f78253cfc946a1c37956f65R233 for inspiration

**Comment by warpdesign** [comment]
@auchenberg I think this issue can be closed.
