### ISSUE TITLE
Lags in 1.32.3

### ISSUE THREAD

**Issue by sh7dm** [auchenberg/vscode-browser-preview#74]
Preview is laggy in VS Code v1.32.3.

**Comment by sh7dm** [comment]
Looks like it's related to #75 because of method of displaying image.

**Comment by sh7dm** [comment]
OS: Ubuntu 18.04, latest updates

**Comment by auchenberg** [comment]
Yup, this is a know issue due to the limitations of Chrome Headless. See https://github.com/auchenberg/vscode-browser-preview/issues/21

**Comment by sh7dm** [comment]
:(, but the project itself is very nice! Good job!

**Comment by auchenberg** [comment]
Thanks @sh7dm !
