### ISSUE TITLE
Small Problem with this extension

### ISSUE THREAD

**Issue by SirTwsted** [auchenberg/vscode-browser-preview#76]
Anything I do, opened the panel of Browser Preview.
im not even requesting to preview it and yet it opens all by itself.
If I click on empty space, it opens.  If I select a different file or folder in the sideBar, it opens.
If I look at VS Code the wrong way, it opens.
I had no choice but to disable the extension, because I was afraid to touch VS code,
because the Browser Preview window would open.   :/

**Comment by auchenberg** [comment]
Dup of #58
