### ISSUE TITLE
Browser preview causes GPU process 100% on Pixelbook

### ISSUE THREAD

**Issue by mhofman** [auchenberg/vscode-browser-preview#78]
Launching browser preview on a Pixelbook, with VSCode installed using Linux Apps (aka crostini), the GPU process shoots up to 100%, and the whole system becomes unresponsive.

**Comment by mhofman** [comment]
Probably duplicate of https://github.com/auchenberg/vscode-browser-preview/issues/21

**Comment by auchenberg** [comment]
Dup of #21
