### ISSUE TITLE
Infinite loop in calculateViewportSize  because of sub-pixel dimensions

### ISSUE THREAD

**Issue by IllusionMH** [auchenberg/vscode-browser-preview#81]
Initially was spotted/discussed in #37 .

Infinite re-render loop caused by sub-pixel dimension is still there and f414aec doesn't fix the problem.

Root cause of this issue ATM - different processing of subpixel values:
`roundNumber` in [viewport.tsx](https://github.com/auchenberg/vscode-browser-preview/blob/master/src/components/viewport/viewport.tsx#L230-L232) will round to 2 decimal digits, and this value will be compared with `viewportMetadata` that had same dimensions passed through `Math.floor` in [App.tsx](https://github.com/auchenberg/vscode-browser-preview/blob/master/src/App.tsx#L331-L332)
Both of linked places should have same rounding mechanism.

In my case it was just enough to slightly resize window to get stuck in this infinite loop when viewport size became `459.3333435058594` (rounded `459.33`, compared to `viewportMetadata` value `459`)

**Comment by auchenberg** [comment]
Good catch @IllusionMH. Hereby using `math.floor` consistently everywhere.
