### ISSUE TITLE
Feature request: Use any chromium-based browser like MS Edge

### ISSUE THREAD

**Issue by WSLUser** [auchenberg/vscode-browser-preview#86]
Windows Insiders features a revamped Microsoft Edge powered by Chromium. I would prefer to use it in place of Chrome in instances where the Windows version is supported (the April 2019 release).

**Update (Sep 2020)**: There's a stand-alone msi you can use to install it. Also, it's possible for any chromium based browser to be used so all of them should be detectable by the extension.

**Comment by IllusionMH** [comment]
You should be able just specify path to your `msedge.exe` installation as Chrome Executable.
Or in config for your user name:
```json
    "browser-preview.chromeExecutable": "C:\\Users\\<user name>\\AppData\\Local\\Microsoft\\Edge SxS\\Application\\msedge.exe"
```

**Comment by WSLUser** [comment]
I will give that a try once it hits the stable release.

**Comment by auchenberg** [comment]
This is a good idea, since Edge is based on Chromium and the used APIs are somewhat stable. Right now we use `which-chrome` to detect the Chrome installation, but this could easily be modified to detect any compatible Chromium verison

**Comment by texastoland** [comment]
I don't know if it helps, but I looked into this a little. `which-chrome` appears to be deprecated by `chrome-paths`. Both are wrappers around `karma-chrome-launcher`. There appears to be a new unofficial [`karma-chromium-edge-launcher`](https://yarnpkg.com/package/@chiragrupani/karma-chromium-edge-launcher). Perhaps you could get it by calling each directly?

**Comment by WSLUser** [comment]
I'm wondering if this project really gets any maintenance at all. The last PR is from 2019 while the last commit is simply dropping a dependency in July.  It may need forking to actually address all the issues this repo has, starting with this one (the ability to launch any chromium browser, not just Chrome, would be a great feature to start with in a new fork).

**Comment by auchenberg** [comment]
@WSLUser Want to become a maintainer of the project? I'd love some more hands helping out.

**Comment by texastoland** [comment]
> You should be able just specify path to your `msedge.exe` installation as Chrome Executable.
> Or directly in `settings.json` for your user name:

PS the Mac equivalent is:

```json
// path specifically for Edge Dev release
"browser-preview.chromeExecutable": "/Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev",
```

**Comment by WSLUser** [comment]
I myself can't but I do hope others will step up. I think you creating this project is great and just needs some refinement. Life gets in the way and that's understandable. Maybe if you do have code just sitting around you mess with can exist in another branch so others can help add to it to bring to fruition whatever you started work on but never finished.

**Comment by auchenberg** [comment]
Landed.
