### ISSUE TITLE
Format configuration not working?

### ISSUE THREAD

**Issue by warpdesign** [auchenberg/vscode-browser-preview#89]
While trying to reduce blurry I set the format to `png` but it doesn't seem to work. The image tag which is generated still seems to contain jpg data:

![image](https://user-images.githubusercontent.com/199648/56051885-4fda8a80-5d50-11e9-98f1-050a9e2bdcfe.png)

```
<img src="data:image/jpg..."/>
```

**Comment by warpdesign** [comment]
Actually the base64 data contains png data, it's just the src base64 header that wrongly indicates jpg. Luckily Chrome doesn't seem to care...

**Comment by warpdesign** [comment]
I made a fix for that: this won't remove the blur effect but at least that's one bug removed :)

**Comment by auchenberg** [comment]
Good catch @warpdesign!

Since you already are peaking under the surface. Can you compare the rendered image on the `<img>` to the rendered output on the `<canvas>` and see if there's a difference in clarity? My experience is that on some machines and DPIs the canvas is blurry, while the image frame is clear.

**Comment by warpdesign** [comment]
@auchenberg Already had a look: image is already blurry in `<img>` tag.

The following screenshot shows the render:

 1. in Chrome (outside VSCode)
 2. in VSCode/canvas tag
 3. in VSCode/img tag

![image](https://user-images.githubusercontent.com/199648/56055750-a947b700-5d5a-11e9-8a81-b50a45539e6d.png)

As you can see it's already blurry in the img tag. I'm not sure I understand everything correctly yet:

It's the image captured data from the headless Chrome that you receive, put in the img tag, and then draw into the canvas? Or am I missing something?

**Comment by auchenberg** [comment]
Yes, that flow is correct. Browser Preview is "remote controlling" Chrome Headless and asking for a stream of images, which are streamed over the DevTools protocol, base64 Decoded via the <img> and then rendered on the <canvas>.

If Chrome already sends us a blurry image, then we can't do much :/ I'm wondering if there's some settings or tweaks we can make.

**Comment by auchenberg** [comment]
What if you increase the quality to `100` in https://github.com/auchenberg/vscode-browser-preview/blob/master/src/App.tsx#L237 @warpdesign Does that changes things for you?

**Comment by warpdesign** [comment]
Modifying quality doesn't seem to change anything (tried with jpeg only since I guess it's only used in jpeg). Tried setting it to 100, then lowering it to 0 and quality appears to be the same as with the default 80 setting: weird.

Maybe it's not fully implemented since [page.startScreencast](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-startScreencast) is experimental?

**Comment by warpdesign** [comment]
What's sure is that the higher the DPI, the less we see compression artifacts (like blurriness) so it's not surprising it less/not visible in high DPI.

**Comment by auchenberg** [comment]
@warpdesign Can you try to pull master? I think this might be it for non-DPI monitors. https://github.com/auchenberg/vscode-browser-preview/commit/c8ee168848c9109cb8e36c19403ee676bac6f33b

**Comment by warpdesign** [comment]
@auchenberg We're getting there: the image appears to be correct now, but it's when drawn onto the canvas that it gets blurry now.

I have an idea.

**Comment by warpdesign** [comment]
Here is what I found:
 - removing `max-width:100%` and `max-height:100%`in the css applied to the image fixes the blurriness on the image
 - the image size is slightly larger (a few pixels only) than the canvas size (see screenshot): that explains why it gets blurry when drawn onto the canvas

**Comment by auchenberg** [comment]
@warpdesign Aha! Good investigation! I shall give it a spin. I've opened https://github.com/auchenberg/vscode-browser-preview/issues/92
