### ISSUE TITLE
Blurry rendering on non-retina

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/vscode-browser-preview#92]
From @warpdesign  Here is what I found out:
 - removing `max-width:100%` and `max-height:100%`in the css applied to the image fixes the blurriness on the image
 - the image size is slightly smaller (a few pixels only) than the canvas size (see screenshot): that explains why it gets blurry when drawn onto the canvas

![image](https://user-images.githubusercontent.com/199648/56076429-2d3c8600-5dd1-11e9-8e05-394533d29c6a.png)

https://github.com/auchenberg/vscode-browser-preview/issues/89#issuecomment-482786179

**Comment by auchenberg** [comment]
Inspiration: https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/screencast/ScreencastView.js?q=screencast&sq=package:chromium&dr=CSs&l=164

**Comment by melMass** [comment]
Any news regarding that issue ?

**Comment by auchenberg** [comment]
@melMass I don't have much time to work on this project these days. If you have time to contribute it would be much appreciated.

**Comment by warpdesign** [comment]
I'll try to find some time to look at this issue.

**Comment by auchenberg** [comment]
Looks like a solution have been found in the fork of BrowserPreview, https://github.com/antfu/vscode-browse-lite/commit/94b4064122aff4a9be515a0d0fe50c51c6ac0f28

**Comment by anburocky3** [comment]
+1

**Comment by anburocky3** [comment]
> Looks like a solution have been found in the fork of BrowserPreview, [antfu/vscode-browse-lite@94b4064](https://github.com/antfu/vscode-browse-lite/commit/94b4064122aff4a9be515a0d0fe50c51c6ac0f28)

In VSCode-browse-lite too, it is blurry.

**Comment by auchenberg** [comment]
Duplicate of https://github.com/auchenberg/vscode-browser-preview/issues/75
