### ISSUE TITLE
How to access & define key/value pairs for application's local storage

### ISSUE THREAD

**Issue by rbadapanda** [auchenberg/vscode-browser-preview#96]
My application reads some key/value from localstorage during start.

Is there a way I can provide that with this extension?
or,
can you please expose the developer tools instance of the browser that is embedded in VScode?

Anyway, thanks for the great tool!

**Comment by auchenberg** [comment]
You can use Chrome Devtools from a separate Chrome instance by going to `chrome://inspect` and setup network discovery on `localhost:9222`. That way you can use Chrome DevTools to inspect

**Comment by pungggi** [comment]
would be nice to be able to launch inspect on that target with a flag it that is possible.
